import type { WindowDefinition } from "../definitions/windowDefinitions";
import AboutContent from "../../../components/window-content/home-window-content/AboutContent";
import ContactContent from "../../../components/window-content/home-window-content/ContactContent";

export const homeWindowRegistry: Record<string, WindowDefinition> = {
  about: {
    id: "about",
    icon: "folder",
    title: "About",
    defaultWidth: 500,
    defaultX: 500,
    defaultY: 80,
    renderContent: () => <AboutContent />,
    defaultOpen: true,
  },
  gallery: {
    id: "gallery",
    icon: "folder",
    title: "Gallery",
    defaultWidth: 600,
    defaultHeight: 450,
    defaultX: 200,
    defaultY: 120,
  },
  featuredWork: {
    id: "featuredWork",
    icon: "folder",
    title: "Featured Work",
    defaultWidth: 600,
    defaultHeight: 450,
    defaultX: 260,
    defaultY: 160,
  },
  featuredExperiment: {
    id: "featuredExperiment",
    icon: "folder",
    title: "Featured Experiment",
    defaultWidth: 600,
    defaultHeight: 450,
    defaultX: 80,
    defaultY: 140,
  },
  notes: {
    id: "notes",
    // icon: "note",
    icon: "folder",
    title: "Notes",
    defaultWidth: 400,
    // defaultHeight: 500,
    defaultX: 150,
    defaultY: 70,
  },
  contact: {
    id: "contact",
    // icon: "mail",
    icon: "folder",
    title: "Contact",
    defaultWidth: 400,
    defaultX: 200,
    defaultY: 260,
    renderContent: () => <ContactContent />,
    defaultOpen: true,
  },
  // featuredBlog: {
  //   id: "featuredBlog",
  //   icon: "note",
  //   title: "Featured Blog",
  //   defaultWidth: 500,
  //   defaultHeight: 400,
  //   defaultX: 160,
  //   defaultY: 100,
  // },
};
